<?php
$helper         = $this->helper('Magepow\Crispchat\Helper\Data');
$crispWebsiteId = $helper->getConfigModule('general/crisp_website_id');
if(!$crispWebsiteId) return;
?>
<script type="text/javascript">
    require(['jquery'], function($){
        "use strict";
        $("body").one("mousemove", function() {
            window.$crisp=[];window.CRISP_WEBSITE_ID="<?php echo $crispWebsiteId ?>";(function(){let d=document; let s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();
        });
    });
</script>